spring:
  application:
    name: reservations

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}&ssl=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    org.springframework: INFO
    io.r2dbc.postgresql: DEBUG