name: Deploy Reservation App to AWS Fargate
on:
  push:
    branches:
      - trunk
    paths:
      - reservations/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_GITHUB_OIDC_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Debug identity (opcional pero útil)
        run: aws sts get-caller-identity

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew
        working-directory: reservations

      - name: Build JAR with Gradle
        run: ./gradlew clean build -x test
        working-directory: reservations

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image
        run: |
          DATE=$(date +'%Y%m%d')
          IMAGE_TAG=reservation-${DATE}.${GITHUB_RUN_NUMBER}
          ECR_REGISTRY="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com"
          REPO_NAME="${{ vars.ECR_REPOSITORY }}"
          FULL_IMAGE_URI="$ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG"
          
          docker build -t reservation-app:$IMAGE_TAG .
          docker tag reservation-app:$IMAGE_TAG $FULL_IMAGE_URI
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }}:$IMAGE_TAG
          docker push $FULL_IMAGE_URI
          echo "image=$FULL_IMAGE_URI" >> $GITHUB_OUTPUT
        working-directory: reservations

      - name: Prepare task definition
        env:
          AWS_ECS_EXECUTION_ROLE_ARN: ${{ secrets.AWS_ECS_EXECUTION_ROLE_ARN }}
          AWS_SECRET_DB_USERNAME_ARN: ${{ secrets.AWS_SECRET_DB_USERNAME_ARN }}
          AWS_SECRET_DB_PASSWORD_ARN: ${{ secrets.AWS_SECRET_DB_PASSWORD_ARN }}
          RDS_DB_HOST: ${{ vars.RDS_DB_HOST }}
          RDS_DB_NAME: ${{ vars.RDS_DB_NAME }}
          RDS_DB_SCHEMA: ${{ vars.RDS_DB_SCHEMA }}
          CONTAINER_NAME: 'reservation-app'
          AWS_ECR_IMAGE_URL: ${{ steps.build-image.outputs.image }} # Tomado del output de arriba 🪄
        run: |
          # Sustitución limpia de variables en el archivo JSON
          envsubst '$AWS_ECS_EXECUTION_ROLE_ARN,$AWS_SECRET_DB_USERNAME_ARN,$AWS_SECRET_DB_PASSWORD_ARN,$RDS_DB_HOST,$RDS_DB_NAME,$RDS_DB_SCHEMA,$CONTAINER_NAME,$AWS_ECR_IMAGE_URL' < task-definition.json > task-def.json
        working-directory: reservations

      - name: Deploy to Amazon ECS Fargate
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          # Registra este archivo modificado en AWS ECS
          task-definition: reservations/task-def.json
          # El nombre de tu servicio de Fargate en AWS (Puedes usar una variable si cambia)
          service: ${{ vars.ECS_SERVICE }}
          # El nombre de tu clúster de ECS en AWS (Puedes usar una variable si cambia)
          cluster: ${{ vars.ECS_CLUSTER }}
          # GitHub esperará hasta que los contenedores viejos se apaguen y los nuevos estén estables
          wait-for-service-stability: true